# -*- coding: utf-8 -*-

"""
   BaseJsonLib.Controllers.ProfileController

   This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""
import unirest

from BaseJsonLib.APIHelper import APIHelper
from BaseJsonLib.Configuration import Configuration
from BaseJsonLib.APIException import APIException
from BaseJsonLib.Models.CareerSerializer import CareerSerializer
from BaseJsonLib.Models.CareerSerializer import CareerSerializer
from BaseJsonLib.Models.CareerSerializer import CareerSerializer
from BaseJsonLib.Models.CareerSerializer import CareerSerializer
from BaseJsonLib.Models.CareerSerializer import CareerSerializer
from BaseJsonLib.Models.CareerSerializer import CareerSerializer
from BaseJsonLib.Models.CareerSerializer import CareerSerializer
from BaseJsonLib.Models.EducationSerializer import EducationSerializer


class ProfileController(object):


    """A Controller to access Endpoints in the BaseJsonLib API."""

    def create_career_create(self,
                             company_name,
                             job_title,
                             description=None,
                             from_date=None,
                             to_date=None):
        """Does a POST request to /api/v1.0/user/profile/career/.

        List of all work places (careers) of current user

        Args:
            company_name (string): TODO: type description here.
            job_title (string): TODO: type description here.
            description (string, optional): TODO: type description here.
            from_date (DateTime, optional): TODO: type description here.
            to_date (DateTime, optional): TODO: type description here.

        Returns:
            CareerSerializer: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/api/v1.0/user/profile/career/"

        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {

            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",

        }

        # Prepare parameters
        parameters = {
            "company_name": company_name,
            "job_title": job_title,
            "description": description,
            "from_date": from_date,
            "to_date": to_date
        }
        # The body will be multipart data, so set the header
        headers['Content-Type'] = 'multipart/form-data'

        # Prepare and invoke the API call request to fetch the response
        response = unirest.post(query_url, headers=headers, params=parameters)

        # Error handling using HTTP status codes
        if response.code < 200 or response.code > 206:  # 200 = HTTP OK
            raise APIException("HTTP Response Not OK", response.code, response.body) 
    
        # Try to cast response to desired type
        if isinstance(response.body, dict):
            # Response is already in a dictionary, return the object 
            try:
                return CareerSerializer(**response.body)
            except TypeError:
                raise APIException("Invalid JSON returned", response.code, response.body)
        
        # If we got here then an error occured while trying to parse the response
        raise APIException("Invalid JSON returned", response.code, response.body)

    def get_career_list(self,
                        page):
        """Does a GET request to /api/v1.0/user/profile/career/.

        List of all work places (careers) of current user

        Args:
            page (int): TODO: type description here.

        Returns:
            CareerSerializer: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/api/v1.0/user/profile/career/"

        # Process optional query parameters
        query_parameters = {
            "page": page
        }
        query_builder = APIHelper.append_url_with_query_parameters(query_builder, query_parameters)

        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {

            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",

        }

        # Prepare and invoke the API call request to fetch the response
        response = unirest.get(query_url, headers=headers)

        # Error handling using HTTP status codes
        if response.code < 200 or response.code > 206:  # 200 = HTTP OK
            raise APIException("HTTP Response Not OK", response.code, response.body) 
    
        # Try to cast response to desired type
        if isinstance(response.body, dict):
            # Response is already in a dictionary, return the object 
            try:
                return CareerSerializer(**response.body)
            except TypeError:
                raise APIException("Invalid JSON returned", response.code, response.body)
        
        # If we got here then an error occured while trying to parse the response
        raise APIException("Invalid JSON returned", response.code, response.body)

    def update_career_update(self,
                             company_name,
                             job_title,
                             pk,
                             description=None,
                             from_date=None,
                             to_date=None):
        """Does a PUT request to /api/v1.0/user/profile/career/{pk}/.

        List of all work places (careers) of current user

        Args:
            company_name (string): TODO: type description here.
            job_title (string): TODO: type description here.
            pk (string): TODO: type description here.
            description (string, optional): TODO: type description here.
            from_date (DateTime, optional): TODO: type description here.
            to_date (DateTime, optional): TODO: type description here.

        Returns:
            CareerSerializer: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/api/v1.0/user/profile/career/{pk}/"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "pk": pk
        })

        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {

            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",

        }

        # Prepare parameters
        parameters = {
            "company_name": company_name,
            "job_title": job_title,
            "description": description,
            "from_date": from_date,
            "to_date": to_date
        }
        # The body will be multipart data, so set the header
        headers['Content-Type'] = 'multipart/form-data'

        # Prepare and invoke the API call request to fetch the response
        response = unirest.put(query_url, headers=headers, params=parameters)

        # Error handling using HTTP status codes
        if response.code < 200 or response.code > 206:  # 200 = HTTP OK
            raise APIException("HTTP Response Not OK", response.code, response.body) 
    
        # Try to cast response to desired type
        if isinstance(response.body, dict):
            # Response is already in a dictionary, return the object 
            try:
                return CareerSerializer(**response.body)
            except TypeError:
                raise APIException("Invalid JSON returned", response.code, response.body)
        
        # If we got here then an error occured while trying to parse the response
        raise APIException("Invalid JSON returned", response.code, response.body)

    def create_career_update(self,
                             company_name,
                             job_title,
                             pk,
                             description=None,
                             from_date=None,
                             to_date=None):
        """Does a POST request to /api/v1.0/user/profile/career/{pk}/.

        List of all work places (careers) of current user

        Args:
            company_name (string): TODO: type description here.
            job_title (string): TODO: type description here.
            pk (string): TODO: type description here.
            description (string, optional): TODO: type description here.
            from_date (DateTime, optional): TODO: type description here.
            to_date (DateTime, optional): TODO: type description here.

        Returns:
            CareerSerializer: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/api/v1.0/user/profile/career/{pk}/"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "pk": pk
        })

        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {

            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",

        }

        # Prepare parameters
        parameters = {
            "company_name": company_name,
            "job_title": job_title,
            "description": description,
            "from_date": from_date,
            "to_date": to_date
        }
        # The body will be multipart data, so set the header
        headers['Content-Type'] = 'multipart/form-data'

        # Prepare and invoke the API call request to fetch the response
        response = unirest.post(query_url, headers=headers, params=parameters)

        # Error handling using HTTP status codes
        if response.code < 200 or response.code > 206:  # 200 = HTTP OK
            raise APIException("HTTP Response Not OK", response.code, response.body) 
    
        # Try to cast response to desired type
        if isinstance(response.body, dict):
            # Response is already in a dictionary, return the object 
            try:
                return CareerSerializer(**response.body)
            except TypeError:
                raise APIException("Invalid JSON returned", response.code, response.body)
        
        # If we got here then an error occured while trying to parse the response
        raise APIException("Invalid JSON returned", response.code, response.body)

    def update_career_partial_update(self,
                                     pk,
                                     company_name=None,
                                     description=None,
                                     from_date=None,
                                     job_title=None,
                                     to_date=None):
        """Does a PATCH request to /api/v1.0/user/profile/career/{pk}/.

        List of all work places (careers) of current user

        Args:
            pk (string): TODO: type description here.
            company_name (string, optional): TODO: type description here.
            description (string, optional): TODO: type description here.
            from_date (DateTime, optional): TODO: type description here.
            job_title (string, optional): TODO: type description here.
            to_date (DateTime, optional): TODO: type description here.

        Returns:
            CareerSerializer: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/api/v1.0/user/profile/career/{pk}/"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "pk": pk
        })

        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {

            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",

        }

        # Prepare parameters
        parameters = {
            "company_name": company_name,
            "description": description,
            "from_date": from_date,
            "job_title": job_title,
            "to_date": to_date
        }
        # The body will be multipart data, so set the header
        headers['Content-Type'] = 'multipart/form-data'

        # Prepare and invoke the API call request to fetch the response
        response = unirest.patch(query_url, headers=headers, params=parameters)

        # Error handling using HTTP status codes
        if response.code < 200 or response.code > 206:  # 200 = HTTP OK
            raise APIException("HTTP Response Not OK", response.code, response.body) 
    
        # Try to cast response to desired type
        if isinstance(response.body, dict):
            # Response is already in a dictionary, return the object 
            try:
                return CareerSerializer(**response.body)
            except TypeError:
                raise APIException("Invalid JSON returned", response.code, response.body)
        
        # If we got here then an error occured while trying to parse the response
        raise APIException("Invalid JSON returned", response.code, response.body)

    def get_career_retrieve(self,
                            pk):
        """Does a GET request to /api/v1.0/user/profile/career/{pk}/.

        List of all work places (careers) of current user

        Args:
            pk (string): TODO: type description here.

        Returns:
            CareerSerializer: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/api/v1.0/user/profile/career/{pk}/"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "pk": pk
        })

        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {

            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",

        }

        # Prepare and invoke the API call request to fetch the response
        response = unirest.get(query_url, headers=headers)

        # Error handling using HTTP status codes
        if response.code < 200 or response.code > 206:  # 200 = HTTP OK
            raise APIException("HTTP Response Not OK", response.code, response.body) 
    
        # Try to cast response to desired type
        if isinstance(response.body, dict):
            # Response is already in a dictionary, return the object 
            try:
                return CareerSerializer(**response.body)
            except TypeError:
                raise APIException("Invalid JSON returned", response.code, response.body)
        
        # If we got here then an error occured while trying to parse the response
        raise APIException("Invalid JSON returned", response.code, response.body)

    def delete_career_destroy(self,
                              pk):
        """Does a DELETE request to /api/v1.0/user/profile/career/{pk}/.

        List of all work places (careers) of current user

        Args:
            pk (string): TODO: type description here.

        Returns:
            CareerSerializer: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/api/v1.0/user/profile/career/{pk}/"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "pk": pk
        })

        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {

            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",

        }

        # Prepare and invoke the API call request to fetch the response
        response = unirest.delete(query_url, headers=headers)

        # Error handling using HTTP status codes
        if response.code < 200 or response.code > 206:  # 200 = HTTP OK
            raise APIException("HTTP Response Not OK", response.code, response.body) 
    
        # Try to cast response to desired type
        if isinstance(response.body, dict):
            # Response is already in a dictionary, return the object 
            try:
                return CareerSerializer(**response.body)
            except TypeError:
                raise APIException("Invalid JSON returned", response.code, response.body)
        
        # If we got here then an error occured while trying to parse the response
        raise APIException("Invalid JSON returned", response.code, response.body)

    def update_education_partial_update(self,
                                        pk,
                                        city=None,
                                        degree=None,
                                        field_of_study=None,
                                        from_date=None,
                                        notes=None,
                                        school_name=None,
                                        to_date=None):
        """Does a PATCH request to /api/v1.0/user/profile/education/{pk}/.

        List of all schools of current user

        Args:
            pk (string): TODO: type description here.
            city (string, optional): TODO: type description here.
            degree (string, optional): e.g. Bachelor, Magister, PhD, etc
            field_of_study (string, optional): TODO: type description here.
            from_date (DateTime, optional): TODO: type description here.
            notes (string, optional): TODO: type description here.
            school_name (string, optional): TODO: type description here.
            to_date (DateTime, optional): TODO: type description here.

        Returns:
            EducationSerializer: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/api/v1.0/user/profile/education/{pk}/"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "pk": pk
        })

        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {

            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",

        }

        # Prepare parameters
        parameters = {
            "city": city,
            "degree": degree,
            "field_of_study": field_of_study,
            "from_date": from_date,
            "notes": notes,
            "school_name": school_name,
            "to_date": to_date
        }
        # The body will be multipart data, so set the header
        headers['Content-Type'] = 'multipart/form-data'

        # Prepare and invoke the API call request to fetch the response
        response = unirest.patch(query_url, headers=headers, params=parameters)

        # Error handling using HTTP status codes
        if response.code < 200 or response.code > 206:  # 200 = HTTP OK
            raise APIException("HTTP Response Not OK", response.code, response.body) 
    
        # Try to cast response to desired type
        if isinstance(response.body, dict):
            # Response is already in a dictionary, return the object 
            try:
                return EducationSerializer(**response.body)
            except TypeError:
                raise APIException("Invalid JSON returned", response.code, response.body)
        
        # If we got here then an error occured while trying to parse the response
        raise APIException("Invalid JSON returned", response.code, response.body)
