# -*- coding: utf-8 -*-

"""
   BaseJsonLib.Configuration

   This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""

class Configuration :
    # The base Uri for API calls
    BASE_URI = "http://192.168.1.177:10000"


