# -*- coding: utf-8 -*-

"""
   BaseJsonLib.Models.EducationSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""
from BaseJsonLib.APIHelper import APIHelper

class EducationSerializer(object):

    """Implementation of the 'EducationSerializer' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        created (DateTime): TODO: type description here.
        updated (DateTime): TODO: type description here.
        school_name (string): TODO: type description here.
        from_date (DateTime): TODO: type description here.
        to_date (DateTime): TODO: type description here.
        city (string): TODO: type description here.
        degree (string): e.g. Bachelor, Magister, PhD, etc
        field_of_study (string): TODO: type description here.
        notes (string): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the EducationSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    id -- string -- Sets the attribute id
                    created -- DateTime -- Sets the attribute created
                    updated -- DateTime -- Sets the attribute updated
                    school_name -- string -- Sets the attribute school_name
                    from_date -- DateTime -- Sets the attribute from_date
                    to_date -- DateTime -- Sets the attribute to_date
                    city -- string -- Sets the attribute city
                    degree -- string -- Sets the attribute degree
                    field_of_study -- string -- Sets the attribute field_of_study
                    notes -- string -- Sets the attribute notes
        
        """
        # Set all of the parameters to their default values
        self.id = None
        self.created = None
        self.updated = None
        self.school_name = None
        self.from_date = None
        self.to_date = None
        self.city = None
        self.degree = None
        self.field_of_study = None
        self.notes = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "id": "id",
            "created": "created",
            "updated": "updated",
            "school_name": "school_name",
            "from_date": "from_date",
            "to_date": "to_date",
            "city": "city",
            "degree": "degree",
            "field_of_study": "field_of_study",
            "notes": "notes",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "id": "id",
            "created": "created",
            "updated": "updated",
            "school_name": "school_name",
            "from_date": "from_date",
            "to_date": "to_date",
            "city": "city",
            "degree": "degree",
            "field_of_study": "field_of_study",
            "notes": "notes",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)