# -*- coding: utf-8 -*-

"""
   BaseJsonLib.Models.InvitationRequestSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""
from BaseJsonLib.APIHelper import APIHelper
from BaseJsonLib.Models.RoleEnum import RoleEnum

class InvitationRequestSerializer(object):

    """Implementation of the 'InvitationRequestSerializer' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        created (DateTime): TODO: type description here.
        updated (DateTime): TODO: type description here.
        first_name (string): TODO: type description here.
        last_name (string): TODO: type description here.
        phone (string): TODO: type description here.
        email (string): TODO: type description here.
        company_name (string): TODO: type description here.
        role (RoleEnum): TODO: type description here.
        company (string): TODO: type description here.
        invitation (string): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the InvitationRequestSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    id -- string -- Sets the attribute id
                    created -- DateTime -- Sets the attribute created
                    updated -- DateTime -- Sets the attribute updated
                    first_name -- string -- Sets the attribute first_name
                    last_name -- string -- Sets the attribute last_name
                    phone -- string -- Sets the attribute phone
                    email -- string -- Sets the attribute email
                    company_name -- string -- Sets the attribute company_name
                    role -- RoleEnum -- Sets the attribute role
                    company -- string -- Sets the attribute company
                    invitation -- string -- Sets the attribute invitation
        
        """
        # Set all of the parameters to their default values
        self.id = None
        self.created = None
        self.updated = None
        self.first_name = None
        self.last_name = None
        self.phone = None
        self.email = None
        self.company_name = None
        self.role = None
        self.company = None
        self.invitation = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "id": "id",
            "created": "created",
            "updated": "updated",
            "first_name": "first_name",
            "last_name": "last_name",
            "phone": "phone",
            "email": "email",
            "company_name": "company_name",
            "role": "role",
            "company": "company",
            "invitation": "invitation",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

            # Other objects also need to be initialised properly
            if "role" in kwargs:
                self.role = RoleEnum.from_string(kwargs["role"])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "id": "id",
            "created": "created",
            "updated": "updated",
            "first_name": "first_name",
            "last_name": "last_name",
            "phone": "phone",
            "email": "email",
            "company_name": "company_name",
            "role": "role",
            "company": "company",
            "invitation": "invitation",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)