# -*- coding: utf-8 -*-

"""
BaseJsonLib

This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""

class ProficiencyEnum(object):

    """Implementation of the 'proficiency' enum.

    TODO: type enum description here.

    Attributes:
        EXPERT: TODO: type description here.
        NINJA: TODO: type description here.
        NOVICE: TODO: type description here.
        PROFICIENT: TODO: type description here.

    """

    EXPERT = "expert"

    NINJA = "ninja"

    NOVICE = "novice"

    PROFICIENT = "proficient"


    @classmethod
    def to_string(cls, val):
        """Returns the string equivalent for the Enum.

        """
        for k,v in vars(cls).iteritems():
            if v==val:
                return k

    @classmethod
    def from_string(cls, str):
        """Creates an instance of the Enum from a given string.

        """
        return getattr(cls, str.upper(), None)