# -*- coding: utf-8 -*-

"""
BaseJsonLib

This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""

class ReasonEnum(object):

    """Implementation of the 'reason' enum.

    TODO: type enum description here.

    Attributes:
        POOR_DESIGN: TODO: type description here.
        OTHER: TODO: type description here.

    """

    POOR_DESIGN = "poor_design"

    OTHER = "other"


    @classmethod
    def to_string(cls, val):
        """Returns the string equivalent for the Enum.

        """
        for k,v in vars(cls).iteritems():
            if v==val:
                return k

    @classmethod
    def from_string(cls, str):
        """Creates an instance of the Enum from a given string.

        """
        return getattr(cls, str.upper(), None)