# -*- coding: utf-8 -*-

"""
   BaseJsonLib.Models.WriteTaskSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""
from BaseJsonLib.APIHelper import APIHelper

class WriteTaskSerializer(object):

    """Implementation of the 'WriteTaskSerializer' model.

    TODO: type model description here.

    Attributes:
        name (string): TODO: type description here.
        description (string): TODO: type description here.
        start_date (DateTime): TODO: type description here.
        due_date (DateTime): TODO: type description here.
        cost (string): TODO: type description here.
        project (string): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the WriteTaskSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    name -- string -- Sets the attribute name
                    description -- string -- Sets the attribute description
                    start_date -- DateTime -- Sets the attribute start_date
                    due_date -- DateTime -- Sets the attribute due_date
                    cost -- string -- Sets the attribute cost
                    project -- string -- Sets the attribute project
        
        """
        # Set all of the parameters to their default values
        self.name = None
        self.description = None
        self.start_date = None
        self.due_date = None
        self.cost = None
        self.project = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "name": "name",
            "description": "description",
            "start_date": "start_date",
            "due_date": "due_date",
            "cost": "cost",
            "project": "project",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "name": "name",
            "description": "description",
            "start_date": "start_date",
            "due_date": "due_date",
            "cost": "cost",
            "project": "project",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)