# -*- coding: utf-8 -*-

"""
   BaseJsonLib.Models.WriteInvitationSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""
from BaseJsonLib.APIHelper import APIHelper
from BaseJsonLib.Models.RoleEnum import RoleEnum

class WriteInvitationSerializer(object):

    """Implementation of the 'WriteInvitationSerializer' model.

    TODO: type model description here.

    Attributes:
        first_name (string): TODO: type description here.
        last_name (string): TODO: type description here.
        email (string): TODO: type description here.
        role (RoleEnum): TODO: type description here.
        is_admin (bool): invited user will receive staff permissions inside 
            account
        date_accepted (DateTime): TODO: type description here.
        language (string): The language of invitation  letter that will be
            sent
        user (string): TODO: type description here.
        invited_user (string): TODO: type description here.
        company (string): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the WriteInvitationSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    first_name -- string -- Sets the attribute first_name
                    last_name -- string -- Sets the attribute last_name
                    email -- string -- Sets the attribute email
                    role -- RoleEnum -- Sets the attribute role
                    is_admin -- bool -- Sets the attribute is_admin
                    date_accepted -- DateTime -- Sets the attribute date_accepted
                    language -- string -- Sets the attribute language
                    user -- string -- Sets the attribute user
                    invited_user -- string -- Sets the attribute invited_user
                    company -- string -- Sets the attribute company
        
        """
        # Set all of the parameters to their default values
        self.first_name = None
        self.last_name = None
        self.email = None
        self.role = None
        self.is_admin = None
        self.date_accepted = None
        self.language = None
        self.user = None
        self.invited_user = None
        self.company = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "first_name": "first_name",
            "last_name": "last_name",
            "email": "email",
            "role": "role",
            "is_admin": "is_admin",
            "date_accepted": "date_accepted",
            "language": "language",
            "user": "user",
            "invited_user": "invited_user",
            "company": "company",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

            # Other objects also need to be initialised properly
            if "role" in kwargs:
                self.role = RoleEnum.from_string(kwargs["role"])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "first_name": "first_name",
            "last_name": "last_name",
            "email": "email",
            "role": "role",
            "is_admin": "is_admin",
            "date_accepted": "date_accepted",
            "language": "language",
            "user": "user",
            "invited_user": "invited_user",
            "company": "company",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)