# -*- coding: utf-8 -*-

"""
   BaseJsonLib.Models.WriteEditProfileSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
"""
from BaseJsonLib.APIHelper import APIHelper

class WriteEditProfileSerializer(object):

    """Implementation of the 'WriteEditProfileSerializer' model.

    TODO: type model description here.

    Attributes:
        country (string): TODO: type description here.
        first_name (string): TODO: type description here.
        last_name (string): TODO: type description here.
        city (string): TODO: type description here.
        headline (string): TODO: type description here.
        something_about_me (string): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the WriteEditProfileSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    country -- string -- Sets the attribute country
                    first_name -- string -- Sets the attribute first_name
                    last_name -- string -- Sets the attribute last_name
                    city -- string -- Sets the attribute city
                    headline -- string -- Sets the attribute headline
                    something_about_me -- string -- Sets the attribute something_about_me
        
        """
        # Set all of the parameters to their default values
        self.country = None
        self.first_name = None
        self.last_name = None
        self.city = None
        self.headline = None
        self.something_about_me = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "country": "country",
            "first_name": "first_name",
            "last_name": "last_name",
            "city": "city",
            "headline": "headline",
            "something_about_me": "something_about_me",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "country": "country",
            "first_name": "first_name",
            "last_name": "last_name",
            "city": "city",
            "headline": "headline",
            "something_about_me": "something_about_me",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)